version: 2.1

jobs:
    test:
        docker:
            - image: cimg/node:20.13.1
        steps:
            - checkout

    build:
        docker:
            - image: cimg/node:20.13.1
        steps:
            - checkout
            - run:
                name: Verify Yarn Version
                command: yarn -v
            - run:
                name: Install dependencies
                command: yarn install
            - run:
                name: Build the application
                command: yarn build
            - run:
                name: List directory contents
                command: ls -la
            - persist_to_workspace:
                root: .
                paths: .next/

    deploy_dev_iwcm:
        docker:
            - image: cimg/node:20.13.1
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: Run tests
                command: echo 'replace me with real tests!'
            - run:
                name: Deploy Dev to Heroku
                command: |
                    git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_DEV.git feature/update-config-QA
            - persist_to_workspace:
                root: .
                paths: .next/

    deploy_qa_iwcm:
        docker:
            - image: cimg/node:20.13.1
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: Run tests
                command: echo 'replace me with real tests!'
            - run:
                name: Deploy QA to Heroku
                command: |
                    git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_QA.git feature/update-config-QA
            - persist_to_workspace:
                root: .
                paths: .next/

    deploy_staging_iwcm:
        docker:
            - image: cimg/node:20.13.1
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: Run tests
                command: echo 'replace me with real tests!'
            - run:
                name: Deploy Staging to Heroku
                command: |
                    git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGING.git feature/update-config-QA
            - persist_to_workspace:
                root: .
                paths: .next/

    deploy_prod_iwcm:
        docker:
            - image: cimg/node:20.13.1
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: Run tests
                command: echo 'replace me with real tests!'
            - run:
                name: Deploy Prod to Heroku
                command: |
                    git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git feature/update-config-QA

workflows:
    build_deploy_main:
        jobs:
            - test:
                filters:
                    branches:
                        only:
                            - feature/update-config-QA
            - build:
                requires:
                    - test
            - deploy_dev_iwcm:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            - feature/update-config-QA
            - deploy_qa_iwcm:
                type: approval
                requires:
                    - deploy_dev_iwcm
                filters:
                    branches:
                        only:
                            - feature/update-config-QA
            - deploy_staging_iwcm:
                type: approval
                requires:
                    - deploy_qa_iwcm
                filters:
                    branches:
                        only:
                            - feature/update-config-QA
            - deploy_prod_iwcm:
                type: approval
                requires:
                    - deploy_staging_iwcm
                filters:
                    branches:
                        only:
                            - feature/update-config-QA
