# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
     
      - run:
          name: Run tests
          command: echo 'replace me with real tests!'
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt
  deploy_dev_iwcm:
    docker:
      - image: cimg/node:20.13.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build the application
          command: yarn build
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_DEV.git main
  deploy_qa_iwcm:
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - checkout
      - run:
          name: Run tests
          command: echo 'replace me with real tests!'
      - run:
          name: deploy qa to heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_QA.git main
  deploy_staging_iwcm:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo 'replace me with real tests!'
      - run:
          name: deploy staging to heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGING.git main
  deploy_prod_iwcm:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo 'replace me with real tests!'
      - run:
          name: deploy production to heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git main
workflows:
  build_deploy_main:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      - build:
          requires:
            - test
      - deploy_dev_iwcm:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - deploy_qa_iwcm:
          type: approval
          requires:
            - deploy_dev_iwcm
          filters:
            branches:
              only:
                - main
      - deploy_staging_iwcm:
          type: approval
          requires:
            - deploy_qa_iwcm
          filters:
            branches:
              only:
                - main
      - deploy_prod_iwcm:
          type: approval
          requires:
            - deploy_staging_iwcm
          filters:
            branches:
              only:
                - main
