title: "Complaint Manager 2.0"
theme: "just-the-docs"

search_enabled: true
enable_copy_code_button: true

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  

# NB: If you update this config file, please also update docs/wiki-information/wiki-configuration.md.

# The collections_dir is the directory where the collections are stored.  Only needed if using nested folders
# collections_dir: development-resources

# To implement collections, make a folder "_example" the name is bananable but the underscore infront of the name is very important.
# Inside this folder add your markdown files. Then in the _config.yml file add the following code structured like below.
# The underscore is not necessary in here.  Jekyll will now to look for the folder with the underscore infront of the name. 
collections:
  development-resources:
    output: true
    