title: "Complaint Manager 2.0"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
enable_copy_code_button: true
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
collections:
  how-to:
    permalink: "/:collection/:name"
    output: true
just-the-docs:
  collections:
    how-to:
      name: How To Guides

# TODO: add info about collections to ./wiki-configuration.md

# NB: If you update this config file, please also update docs/wiki-information/wiki-configuration.md.
